version: '2'
services:
  jobmanager:
    image: mesoshq/flink
    container_name: jobmanager
    command: jobmanager
    environment:
        - HOST=jobmanager
        - PORT0=6123
        - PORT1=8081
    ports:
        - "6123:6123" # czy to potrzebne?
        - "8081:8081"
  taskmanager:
    image: mesoshq/flink
    container_name: taskmanager
    command: taskmanager
    environment:
        - flink_jobmanager_rpc_address=jobmanager
        - flink_jobmanager_rpc_port=6123
        - flink_taskmanager_tmp_dirs=/data/tasks
        - flink_blob_storage_directory=/data/blobs
        #- flink_state_backend=filesystem
        - flink_state_backend=jobmanager
        - flink_taskmanager_numberOfTaskSlots=5
        - flink_taskmanager_heap_mb=2048
        - HOST=taskmanager
        - PORT0=7001
        - PORT1=7002
        - PORT2=7003
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
